# Static configuration

entrypoints:
  unsecure:
    address: :80

providers:
  file:
    filename: blockadmin.yaml
    watch: true           # Every time all.yaml changes refresh and pull from the file